name: newlink

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pull-requests: write

jobs:
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
      newlink_changed: ${{ steps.filter.outputs.newlink }}
    steps:
    - uses: actions/checkout@v2
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          infra:
            - 'infra/**'
          newlink:
            - 'newlink/**'
  newlink:
    needs: changes
    if: ${{ needs.changes.outputs.newlink_changed == 'true' }}
    name: Build newlink
    runs-on: ubuntu-22.04
    # defaults:
    #   run:
    #     shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install Cargo Lambda
      run: pip3 install cargo-lambda 
    - name: Build
      working-directory: ./newlink    
      run: cargo lambda build --release

  infra:
    needs: [ changes, newlink ]
    if: ${{ needs.changes.outputs.infra_changed == 'true' }}
    name: Deploy Lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infra    
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6
        terraform_wrapper: false            
    - name: Terraform Init
      id: init
      run: terraform init    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions/validate@v0.3.7
    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          </details>
          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false

    # - name: Sync S3
    #   uses: jakejarvis/s3-sync-action@master
    #   env:
    #     SOURCE_DIR: './src'
    #     AWS_REGION: 'us-east-1'
    #     AWS_S3_BUCKET: '[BUCKET_NAME_HERE]'
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
